const okex = require('./okex');

module.exports = {
  SYMBOL_BTC_USD: 'btc_usd',
  SYMBOL_ETH_USD: 'eth_usd',
  SYMBOL_LTC_USD: 'ltc_usd',
  SYMBOL_BCH_USD: 'bch_usd',
  SYMBOL_ETC_USD: 'etc_usd',
  SYMBOL_EOS_USD: 'eos_usd',

  EXCHANGE_HUOBI: 'hb',
  EXCHANGE_OKEX: 'okex',

  ORDER_STATUS_WAIT: 'wait', //  等待成交订单
  ORDER_STATUS_OPEN: 'open', //  已开仓订单
  ORDER_STATUS_IN: 'in',
  ORDER_STATUS_WIN: 'win',
  ORDER_STATUS_LOSE: 'lose',
  ORDER_STATUS_ERROR: 'error', //  错误入场订单
  ORDER_STATUS_CANCEL: 'cancel', //  取消入场订单
  ORDER_STATUS_TOP: 'top', //  上行通道订单
  ORDER_STATUS_BOTTOM: 'bottom', //  下行通道订单
  ORDER_STATUS_OUT: 'out',
  ORDER_STATUS_LIQUIDATE: 'liquidate', //  已平仓订单
  ORDER_STATUS_LOCK: 'lock',
  ORDER_STATUS_DELETE: 'delete',

  ORDER_TYPE_OPEN_LONG: 'open_long',
  ORDER_TYPE_OPEN_SHORT: 'open_short',
  ORDER_TYPE_LIQUIDATE_LONG: 'liquidate_long',
  ORDER_TYPE_LIQUIDATE_SHORT: 'liquidate_short',

  ORDER_DIRECTION_LEFT: 'left',
  ORDER_DIRECTION_RIGHT: 'right',

  INTERVAL_LEVEL_NORMAL: 5000,
  INTERVAL_LEVEL_FAST: 3000,
  INTERVAL_LEVEL_FASTER: 1000,
  INTERVAL_LEVEL_FASTEST: 300,

  CUMSUM_LEVEL_NORMAL: 30000,
  CUMSUM_LEVEL_FAST: 20000,
  CUMSUM_LEVEL_FASTER: 10000,
  CUMSUM_LEVEL_FASTEST: 3500,

  CONTRACT_TYPE_OKEX_THIS_WEEK: 'this_week',
  CONTRACT_TYPE_OKEX_NEXT_WEEK: 'next_week',
  CONTRACT_TYPE_OKEX_QUARTER: 'quarter',

  LEVER_RATE_OKEX_LEVEL1: 10,
  LEVER_RATE_OKEX_LEVEL2: 20,

  OPEN_LONG_OKEX: 1,
  OPEN_SHORT_OKEX: 2,
  LIQUIDATE_LONG_OKEX: 3,
  LIQUIDATE_SHORT_OKEX: 4,

  DATE_STANDARD_FORMAT: '2017-03-10',
  DATE_SHORT_FORMAT: '20170310',

  DATETIME_SHORT_FORMAT: '20170310000000',
  DATETIME_STANDARD_FORMAT: '2017-03-10 00:00:00',

  KLINE_TYPE_DAY_KLINE: '1day',
  KLINE_TYPE_MIN_KLINE: '1min',

  OKEX: okex,
};
